name: "org-mode export"
on:
  pull_request:
  push:
jobs:
  org-export-html:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v10
      with:
        name: nothingmuch
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - run: nix build .#html
    - run: cp -R result/ html/
    - uses: actions/upload-artifact@v3
      with:
        name: html
        path: html/
    - uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: html/
  org-export-pdf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v10
      with:
        name: nothingmuch
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - run: nix build .#pdf
    - run: cp -R result/ pdf/
    - uses: actions/upload-artifact@v3
      with:
        name: pdf
        path: pdf/
